name: "Publish to GitHub Pages"
on:
  push:
    branches: [ "main", "deployment-automation" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
